### ISSUE TITLE
LICENSE file should be W3C ?

### ISSUE THREAD

**Issue by ayakoakasaka** [midokura/wasi-sensor-discussion#23]
https://github.com/WebAssembly/wasi-proposal-template/blob/main/LICENSE.md
might be good

**Comment by yamt** [comment]
> https://github.com/WebAssembly/wasi-proposal-template/blob/main/LICENSE.md might be good

i don't think this repo is "published by the [WebAssembly Community Group](https://www.w3.org/community/webassembly/)".

**Comment by ayakoakasaka** [comment]
Indeed
